export const cards = {
    Actions: {
            dance: 'танцевать',
            draw: 'рисовать',
            jump: 'прыгать',
            play: 'играть',
            ride: 'ездить',
            run: 'бегать',
            sing: 'петь',
            sleep: 'спать',
            swim: 'плавать',
        },

    Animals: {
        cat: 'кот',
        deer: 'олень',
        dog: 'собака',
        fox: 'лиса',
        horse: 'лошадь',
        mouse: 'мышь',
        rabbit: 'кролик',
        tiger: 'тигр',
        turtle: 'черепаха',
    },
    Body: {
        back: 'спина',
        ear: 'ухо',
        eye: 'глаз',
        hand: 'рука',
        head: 'голова',
        leg: 'нога',
        lip: 'губа',
        neck: 'шея',
        nose: 'нос',
    },
    Clothes: {
        dress: 'платье',
        glove: 'перчатка',
        hat: 'шапка',
        pants: 'штаны',
        scarf: 'шарф',
        shirt: 'рубашка',
        shoe: 'туфля',
        skirt: 'юбка',
        sock: 'носок',
    },
    Emotions: {
        anger: 'злость',
        cry: 'плач',
        fear: 'страх',
        joy: 'веселье',
        shout: 'крик',
        shyness: 'застенчивость',
        smile: 'улыбка',
        sorrow: 'печаль',
        wonder: 'удивление',
    },
    Family: {
        aunt: 'тетя',
        baby: 'младенец',
        brother: 'брат',
        father: 'отец',
        grandfather: 'дедушка',
        grandmother: 'бабушка',
        mother: 'мама',
        sister: 'сестра',
        uncle: 'дядя',
    },
    Food: {
        apple: 'яблоко',
        banana: 'банан',
        bread: 'хлеб',
        cake: 'торт',
        cheese: 'сыр',
        donut: 'пончик',
        egg: 'яйцо',
        milk: 'молоко',
        tomato: 'помидор',
    },
    Nature: {
        beach: 'пляж',
        desert: 'пустыня',
        flower: 'цветок',
        forest: 'лес',
        lake: 'озеро',
        rain: 'дождь',
        rainbow: 'радуга',
        river: 'река',
        snow: 'снег',
    },
};
